question_data = [
    {"question": "A slug's blood is green.", "correct_answer": "True"},
    {"question": "The loudest animal is the African Elephant.",
        "correct_answer": "False"},
    {"question": "Approximately one quarter of human bones are in the feet.",
        "correct_answer": "True"},
    {"question": "The total surface area of a human lungs is the size of a football pitch.",
        "correct_answer": "True"},
    {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "correct_answer": "True"},
    {"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
        "correct_answer": "False"},
    {"question": "It is illegal to pee in the Ocean in Portugal.",
        "correct_answer": "True"},
    {"question": "You can lead a cow down stairs but not up stairs.",
        "correct_answer": "False"},
    {"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
    {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.",
        "correct_answer": "True"},
    {"question": "No piece of square dry paper can be folded in half more than 7 times.",
        "correct_answer": "False"},
    {"question": "A few ounces of chocolate can to kill a small dog.",
        "correct_answer": "True"},
    {"question": 'The commercial UK channel ITV stands for "International Television".',
        "correct_answer": "False"},
    {"question": 'King Gizzard & The Lizard Wizard\'s album "Nonagon Infinity" can be looped seamlessly.',
        "correct_answer": "True"},
    {"question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.", "correct_answer": "False"},
    {"question": 'This is the correct spelling of "Supercalifragilisticexpialidocious".',
        "correct_answer": "True"},
    {"question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
        "correct_answer": "True"},
    {"question": "A pasodoble is a type of Italian pasta sauce.",
        "correct_answer": "False"},
    {"question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
        "correct_answer": "True"},
    {"question": "Vietnam's national flag is a red star in front of a yellow background.",
        "correct_answer": "False"},
    {"question": "You can legally drink alcohol while driving in Mississippi.",
        "correct_answer": "True"},
    {"question": "Albert Einstein had trouble with mathematics when he was in school.",
        "correct_answer": "False"},
    {"question": "March 10th is also known as Mar10 Day.", "correct_answer": "True"},
    {"question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.", "correct_answer": "False"},
    {"question": "Dihydrogen Monoxide is a dangerous chemical.",
        "correct_answer": "False"},
    {"question": '"Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo." is a grammatically correct sentence.', "correct_answer": "True"},
    {"question": 'NCIS stands for "Navy Corps Investigative Service".',
        "correct_answer": "False"},
    {"question": "Gumbo is a stew that originated in Louisiana.",
        "correct_answer": "True"},
    {"question": "The vapor produced by e-cigarettes is actually water.",
        "correct_answer": "False"},
    {"question": "Cucumbers are usually more than 90% water.", "correct_answer": "True"},
    {"question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
        "correct_answer": "True"},
    {"question": "Pluto is a planet.", "correct_answer": "False"},
    {"question": "Sitting for more than three hours a day can cut two years off a person's life expectancy.",
        "correct_answer": "True"},
    {"question": "A pencil's lead is typically made from graphite, not lead",
        "correct_answer": "True"},
    {"question": "Furby was released in 1998.", "correct_answer": "True"},
    {"question": 'The French word for "glass" is "glace".', "correct_answer": "False"},
    {"question": "All strawberries are red.", "correct_answer": "False"},
    {"question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian.",
        "correct_answer": "True"},
    {"question": 'The term "Spam" came before the food product "Spam".',
        "correct_answer": "False"},
    {"question": '"Typewriter" is the longest word that can be typed using only the first row on a QWERTY keyboard.',
        "correct_answer": "False"},
    {"question": "French is an official language in Canada.", "correct_answer": "True"},
    {"question": "The average woman is 5 inches / 13 centimeters shorter than the average man.",
        "correct_answer": "True"},
    {"question": '"Ananas" is mostly used as the word for Pineapple in other languages.',
        "correct_answer": "True"},
    {"question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True"},
    {"question": "You are allowed to sell your soul on eBay.",
        "correct_answer": "False"},
    {"question": "The National Animal of Scotland is the Unicorn.",
        "correct_answer": "True"},
    {"question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.", "correct_answer": "False"},
    {"question": "In Scandinavian languages, the letter Å means river.",
        "correct_answer": "True"},
    {"question": "The color orange is named after the fruit.", "correct_answer": "True"},
    {"question": "The sum of all the numbers on a roulette wheel is 666.",
        "correct_answer": "True"},
    {"question": '"Number 16 Bus Shelter" was a child\'s name that was approved by the New Zealand government.',
        "correct_answer": "True"},
    {"question": "Ping-Pong originated in England", "correct_answer": "True"},
    {"question": "An eggplant is a vegetable.", "correct_answer": "False"},
    {"question": "Slovakia is a member of European Union", "correct_answer": "True"},
    {"question": "When you cry in space, your tears stick to your face.",
        "correct_answer": "True"},
    {"question": "The mitochondria is the powerhouse of the cell.",
        "correct_answer": "True"},
    {"question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
        "correct_answer": "False"},
    {"question": "Is a dog a mammal?", "correct_answer": "True"},
    {"question": 'Stagecoach owned "South West Trains" before losing the rights to FirstGroup and MTR in March of 2017.',
        "correct_answer": "True"},
    {"question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.", "correct_answer": "True"},
    {"question":
        'The word "news" originates from the first letters of the 4 main directions on a compass (North, East, West, South).', "correct_answer": "False"},
    {"question": '"27 Club" is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.', "correct_answer": "True"},
    {"question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.", "correct_answer": "True"},
    {"question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
        "correct_answer": "True"},
    {"question": "Route 66 in the United States spans the entire mainland of America, from California to New York.",
        "correct_answer": "False"},
    {"question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series' history.",
        "correct_answer": "True"},
    {"question": "The Republic of Malta is the smallest microstate worldwide.",
        "correct_answer": "False"},
    {"question": "Linus Torvalds created Linux and Git.", "correct_answer": "True"},
    {"question": "Thomas Crapper was a plumber who invented the flushing toilet.",
        "correct_answer": "False"},
    {"question":
        "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).", "correct_answer": "True"},
    {"question": "The Sniper's SMG in Team Fortress 2, was originally intended to be the Scout's primary weapon.",
        "correct_answer": "True"},
    {"question": "El Niño pushes warm water to the coasts of the Western Pacific during winter.",
        "correct_answer": "True"},
    {"question": "Pablo Picasso is one of the founding fathers of \"Cubism.\"",
        "correct_answer": "True"},
    {"question": "Greenland is covered with grass and Iceland covered with ice.",
        "correct_answer": "False"},
    {"question": "In \"Minecraft\", gold tools are faster than diamond tools.",
        "correct_answer": "True"},
    {"question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
        "correct_answer": "False"},
    {"question": "George Lucas directed the entire original Star Wars trilogy.",
        "correct_answer": "False"},
    {"question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court.", "correct_answer": "True"},
    {"question": "Super Mario and Paarthurnax (Skyrim) are voiced by the same actor.",
     "correct_answer": "True"},
    {"question": "Skaði is the Norse Goddess of skiing, mountains, winter and bowhunting.",
        "correct_answer": "True"},
    {"question":
        "Great Whites sometimes perform the bump-and-bite attack (a test bite) on victims.", "correct_answer": "True"},
    {"question": "The average lifespan of a wildcat is only around 5-6 years.",
        "correct_answer": "False"},
    {"question": "In World War II, Great Britain used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy/D-day landing.", "correct_answer": "True"},
    {"question": "Zero factorial is equal to zero.", "correct_answer": "False"},
    {"question": "The programming language \"Python\" is based off a modified version of \"JavaScript\".",
        "correct_answer": "False"},
    {"question": "Han Solo's co-pilot and best friend, \"Chewbacca\", is an Ewok.",
        "correct_answer": "False"},
    {"question": "The Beatles' band name was inspired by the band The Crickets.",
        "correct_answer": "True"},
    {"question": "Psychology is the science of behavior and mind.",
        "correct_answer": "True"},
    {"question": "The ghosts in \"Pac-Man\" and \"Ms. Pac-Man\" have completely different behavior.",
        "correct_answer": "True"},
    {"question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
        "correct_answer": "True"},
    {"question": "Rhode Island is actually located on the US mainland, despite its name.",
        "correct_answer": "True"},
    {"question": "Japan has left-hand side traffic.", "correct_answer": "True"},
    {"question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
        "correct_answer": "True"},
    {"question": "Arriva is owned by the Deutsche Bahn.", "correct_answer": "True"},
    {"question": "In the 1988 film \"Akira\", Tetsuo ends up destroying Tokyo.",
        "correct_answer": "True"},
    {"question": "Steel is an alloy of Iron and Carbon.", "correct_answer": "True"},
    {"question": "The French word to travel is \"Travail\"", "correct_answer": "False"},
    {"question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
        "correct_answer": "True"},
    {"question": "EDM label Monstercat signs tracks instead of artists.",
        "correct_answer": "True"},
    {"question": "The band STRFKR was also briefly known as Pyramiddd.",
        "correct_answer": "True"},
    {"question": "Stanley Kubrick's \"Dr. Strangelove\" (1964) originally ended with a large pie fight in the war room.",
     "correct_answer": "True"},
    {"question": "In \"Star Trek\", Klingons are aliens.", "correct_answer": "True"},
    {"question": "The Xenomorph from the science fiction film \"Alien\" has acidic blood.",
        "correct_answer": "True"},
    {"question": "Otters have pockets under their arms for carrying their favourite snacks and rocks.",
        "correct_answer": "True"}
]
